theme: jekyll-theme-minimal
title: "Nanocar"
description: "Molecular cars"
show_downloads: True
navigation:
  - title: KBS - Home
    url: http://kbsezginel.github.io
  - title: Nanocar
    url: /
  - title: Surface Diffusion
    url: surface-diffusion
  - title: Decacylene
    url: decacylene
  - title: Pyrene
    url: pyrene
